<?php 	
	$render = Mage::helper('ms_megamenu/render');
	$menu = $this->getCategories();
?>

<div class="nav-container">
	<ul id="navigation">
		<li class="mmHandler"><a href="#">Shop</a>
			<div id="megaMenu">
			    <div id="mainCategories">
					<?php echo $render->mainCategories($menu);?>
				</div>
				<div id="subMenus">
					<?php foreach ($menu as $i => $item) : ?>
						<?php if ($render->hasChild($item)): ?>
							<?php echo $render->subMenu($i, $item['submenu']) ?>
						<?php endif ?>
					<?php endforeach; ?>
					<div id="featuredProducts">
						<?php echo $render->featuredProducts($this->getFeaturedProducts()); ?>
					</div>			
				</div>		
			</div>
		</li>
		<li><a href="#">Shop</a></li>	
		<li><a href="#">Shop</a></li>
		<li><a href="#">Shop</a></li>
	</ul>
</div>